name: Notify

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: secrets.TELEGRAM_BOT_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != ''
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.2.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 New commit pushed to `developer` branch of repository: **${{ github.repository }}**

            **Commit Hash:** `${{ github.sha }}`
            **Commit Message:** ${{ github.event.head_commit.message }}
